name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - blinker=1.8.2
  - certifi=2024.6.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - dash=2.17.0
  - dash-bootstrap-components=1.6.0
  - dash-core-components=2.0.0
  - dash-html-components=2.0.0
  - dash-table=5.0.0
  - flask=2.2.5
  - idna=3.7
  - importlib_metadata=7.1.0
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - markupsafe=2.1.5
  - nest-asyncio=1.6.0
  - packaging=24.0
  - plotly=5.22.0
  - pyyaml=6.0.1
  - requests=2.32.3
  - retrying=1.3.3
  - six=1.16.0
  - python-slugify=8.0.4  # Note: 'slugify' might need to be replaced by 'python-slugify' for Conda.
  - suds-jurko # Note: 'suds-py3' might correspond to 'suds-jurko' in Conda.
  - tenacity=8.3.0
  - typing_extensions=4.12.2
  - urllib3=2.2.1
  - werkzeug=3.0.3
  - zipp=3.19.2
  - pip
  - pip:
      - suds-py3==1.4.5.0 # suds-py3 may need to be installed with pip as it may not be available in Conda
